name: DigDug
authors: [igwb]
main: me.igwb.DigDug.DigDug
version: 0.1
soft-depend: [WorldEdit, WorldGuard]
commands:
   digdug:
      description: test
      usage: /test
      permission: test.test
      permission-message: You don't have permission to use that command!
   dd:
      description: test
      usage: /test
      permission: test.test
      permission-message: You don't have permission to use that command!